server:
  port: 8010

logging:
  level:
    web: debug
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

spring:
  security:
    oauth2:
     resourceserver:
       jwt:
         issuer-uri: http://localhost:9000

