server:
  port: 8085

spring:
  application:
    name: service-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
    gateway:
      routes:
        - id: nacos-route
          uri: lb://service-gateway-provider
          predicates:
            - Path=/nacos/**
          filters:
            - StripPrefix=1 #删除 nacos前缀

logging:
  level:
    web: debug
    com:
      alibaba:
        cloud: debug
    org:
      springframework:
        cloud: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"
