spring:
  cloud:
    nacos:
      config:
        group: DEFAULT_GROUP
        server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
      binders:
        output:
          destination: test-topic
          content-type: application/json
        input:
          destination: test-topic
          content-type: application/json
          group: test-group
  config:
    import:
      - optional:nacos:user-service-dev.yml?refresh=true  # 监听 DEFAULT_GROUP:test.yml
