spring:
  cloud:
    nacos:
      config:
        group: DEFAULT_GROUP
        server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
  config:
    import:
      - optional:nacos:order-service-dev.yml?refresh=true  # 监听 DEFAULT_GROUP:test.yml