server:
  port: 8087

spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
    #sentinel控制台
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080

  #开启sentinel的支持
feign:
  sentinel:
    enabled: true
  client:
    config.default.loggerLevel: FULL

logging:
  level:
    web: debug
    com:
      example.demo.api.UserApi: debug
      alibaba.cloud: debug
    org:
      springframework.cloud: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"
