server:
  port: 8086

spring:
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos

logging:
  level:
    web: debug
    com:
      alibaba:
        cloud: debug
    org:
      springframework:
        cloud: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"